---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: frontend-v1
    labels:
      app: frontend-v1
    annotations:
      nethopper.io/tag-hub: 'true'
  spec:
    selector:
      matchLabels:
        app: frontend-v1
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    template:
      metadata:
        labels:
          app: frontend-v1
      spec:
        containers:
          - name: frontend
            image: nethopper/demoapp:latest
            envFrom:
              - configMapRef:
                  name: cluster-config
            ports:
              - containerPort: 9080
                protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: backend-v1
    labels:
      app: backend-v1
    annotations:
      nethopper.io/tag-edge: 'true'
  spec:
    selector:
      matchLabels:
        app: backend-v1
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    template:
      metadata:
        labels:
          app: backend-v1
      spec:
        containers:
          - name: backend
            image: nethopper/demoapp:latest
            envFrom:
              - configMapRef:
                  name: cluster-config
            ports:
              - containerPort: 8080
                protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
---
  apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: frontend
      service: frontend
    name: frontend
    annotations:
      nethopper.io/tag-hub: 'true'
  spec:
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
      - IPv4
    ipFamilyPolicy: SingleStack
    ports:
      - nodePort: 31000
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      app: frontend-v1
    sessionAffinity: None
    type: NodePort
