---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: laurie-pv
  namespace: laurie
  labels:
    type: local
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Mi
  hostPath:
    path: "/mount/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laurie-pvc
  namespace: laurie
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Mi
  storageClassName: standard
  volumeName: laurie-pv
---
apiVersion: batch/v1
kind: Job
metadata:
  name: laurie-job
  namespace: laurie
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    spec:
      volumes:
      - name: laurie-storage
        persistentVolumeClaim:
          claimName: laurie-pvc
      containers:
      - name: ubuntu
        image: ubuntu:latest
        command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do timestamp=$(date +%H:%M:%S); echo $timestamp > /mount/data/file.txt; sleep 5; done;" ]
        args: [ "timestamp=$(date +%H:%M:%S); echo $timestamp > /mount/data/file.txt;" ]
        volumeMounts:
        - mountPath: /mount/data
          name: laurie-storage
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laurie-dep
  namespace: laurie
  labels:
    app: laurie
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laurie
  template:
    metadata:
      labels:
        app: laurie
    spec:
      volumes:
      - name: laurie-storage
        persistentVolumeClaim:
          claimName: laurie-pvc
      containers:
      - name: ubuntu
        image: ubuntu:latest
        command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do timestamp=$(date +%H:%M:%S); echo $timestamp > /mount/data/file.txt; sleep 5; done;" ]
        #args: [ "timestamp=$(date +%H:%M:%S); echo $timestamp > /mount/data/file.txt;" ]
        args: [ "cat /mount/data/file.txt; while true; do sleep 5; done;" ]
        volumeMounts:
        - mountPath: /mount/data
          name: laurie-storage
