apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui-deployment
  namespace: open-webui
  #annotations:
    #argocd.argoproj.io/sync-wave: "1"
spec:
  #progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:ollama
        #command: ["bash","curl https://raw.githubusercontent.com/nethopper2/infra-gitops/refs/heads/main/demo/users/chris/nh-favicon-96x96.png > /app/backend/open_webui/static/nh-favicon.png && cp /app/backend/open_webui/static/nh-favicon.png /app/backend/open_webui/static/favicon.png && start.sh"]
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "apt update && apt install wget -y && wget https://raw.githubusercontent.com/nethopper2/infra-gitops/refs/heads/main/demo/users/chris/nh-favicon-96x96.png && cp nh-favicon-96x96.png /app/backend/open_webui/static/favicon.png && sleep 300"]
        #command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do sleep 30; done;" ]
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "1000m"
            memory: "1000Mi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
        env:
        - name: OLLAMA_BASE_URL
          value: "http://ollama-service.open-webui.svc.cluster.local:11434"
        tty: true
        volumeMounts:
        - name: webui-volume
          mountPath: /app/backend/data
        #livenessProbe:
        #  httpGet:
        #    path: /
        #    port: 8080
        #  initialDelaySeconds: 30
        #  periodSeconds: 10
        #  timeoutSeconds: 3
        #readinessProbe:
        #  httpGet:
        #    path: /
        #    port: 8080
        #  initialDelaySeconds: 30
        #  periodSeconds: 10
        #  timeoutSeconds: 3

      volumes:
      - name: webui-volume
        persistentVolumeClaim:
          claimName: open-webui-pvc          
