---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    #argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/hook: PreSync
  name: laurie-pv
  namespace: laurie
  labels:
    type: local
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Mi
  hostPath:
    path: "/mount/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laurie-pvc
  namespace: laurie
  annotations:
    #argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook: PreSync
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Mi
  storageClassName: standard
  volumeName: laurie-pv
---
apiVersion: batch/v1
kind: Job
metadata:
  name: laurie-job-w2
  namespace: laurie
  annotations:
    #argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      volumes:
      - name: laurie-storage
        persistentVolumeClaim:
          claimName: laurie-pvc
      containers:
      - name: ubuntu
        image: ubuntu:latest
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "timestamp=$(date +%H:%M:%S); echo $timestamp > /mount/data/file.txt; cat /mount/data/file.txt" ]
        volumeMounts:
        - mountPath: /mount/data
          name: laurie-storage
      restartPolicy: Never
  backoffLimit: 1
---
apiVersion: batch/v1
kind: Job
metadata:
  name: laurie-job-w3
  namespace: lauriex
  annotations:
    #argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/hook: PostSync
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      volumes:
      - name: laurie-storage
        persistentVolumeClaim:
          claimName: laurie-pvc
      containers:
      - name: ubuntu
        image: ubuntu:latest
        #command: [ "/bin/bash", "-c", "--" ] #working command
        command: [ "/bin/bas", "-c", "--" ] #broken command
        #args: [ "while true; do timestamp=$(date +%H:%M:%S); echo $timestamp > /mount/data/file.txt; sleep 5; done;" ]
        #args: [ "cat /mount/data/file.txt; while true; do sleep 5; done;" ] #working loop command
        args: [ "cat /mount/data/file.txt" ] #working command
        volumeMounts:
        - mountPath: /mount/data
          name: laurie-storage
      restartPolicy: Never
  backoffLimit: 1

