apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ping-service-servicemonitor
  # Change this to the namespace the Prometheus instance is running in
  # namespace: default
  labels:
    app: ping-service
    release: onprem-baremetal-observability-edge
spec:
  selector:
    matchLabels:
      app: ping-service
  endpoints:
  - port: http
    interval: 15s