apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-service-v1
  labels:
    app: ping-service-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-service-v1
  template:
    metadata:
      labels:
        app: ping-service-v1
    spec:
      containers:
      - name: app
        image: nethopper/ping-service:latest
        env:
          - name: PING_URLS
            value: http://frontend.default.svc.cluster.local:8080
