kind: Service
apiVersion: v1
metadata:
  name: ping-service
  labels:
    app: ping-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 2112
    protocol: TCP
    name: http
  selector:
    app: ping-service