apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-prim
  labels:
    application: mongo-prim
  annotations:
    nethopper.io/tag-de: 'true'
spec:
  selector:
    matchLabels:
      application: mongo-prim
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        application: mongo-prim
    spec:
      containers:
        - command:
            - mongod
            - '--replSet'
            - rs0
            - '--bind_ip'
            - '*'
          image: mongo:5.0
          ports:
            - containerPort: 27017
              protocol: TCP
          imagePullPolicy: Always
          name: mongo-prim
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: mongodb-data
