apiVersion: v1
kind: Service
metadata:
  name: mongo-prim
  labels:
    app: mongo-prim
    service: mongo-prim
spec:
  ports:
    - port: 27017
      name: http
  selector:
    application: mongo-prim
