apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: open-webui
  name: open-webui-pvc
  namespace: open-webui
spec:
  storageClassName: gp2
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
